Bundle update dependencies
Some changes to ActiveSupport mean that we need an additional `require "active_support"`
to avoid the error

   Failure/Error: require "active_support/core_ext/time/conversions"
   NoMethodError:
     undefined method `deprecator' for ActiveSupport:Module
       deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                               ^^^^^^^^^^^

See here for details of standalone Active Support:
https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support